### ISSUE TITLE
Variance in the function drawing b

### ISSUE THREAD

**Issue by kprinceing** [mbaker21231/BayesMixedLogit#1]
In chapter 12 of Train's book , the variance of drawing b from known variance, unknown mean is W/N. In your function, it seems that you use W instead of W/N.

**Comment by kprinceing** [comment]
Never mind. I realized that you used W/N in the MCMC draw. Sorry about the confusion.

**Comment by mbaker21231** [comment]
@kprinceing --

Sorry for not responding sooner; I just saw this! In any event, I really appreciate you taking a look at my code so closely. If you have any ideas/suggestions/comments please let me know!

Best,

@mbaker21231
